<?php

define("BEEM_API_KEY", "YOUR_BEEM_API_KEY");
define("BEEM_SECRET_KEY", "YOUR_BEEM_SECRET_KEY");
define("BEEM_SENDER_ID", "YOUR_SENDER_ID");

define("BEEM_WHATSAPP_API_KEY", "YOUR_WHATSAPP_API_KEY");
define("BEEM_WHATSAPP_SECRET_KEY", "YOUR_WHATSAPP_SECRET_KEY");
define("BEEM_WHATSAPP_FROM_ADDR", "YOUR_WHATSAPP_NUMBER");
define("BEEM_WHATSAPP_API_URL", "YOUR_WHATSAPP_API_ENDPOINT");